"""
compliance_pautas.py — Repositorio centralizado de pautas de auditoría.

Todas las listas de preguntas/ítems de auditoría del sistema CGT.pro
viven aquí. Esto permite:
  - Editar pautas sin tocar lógica de negocio
  - Reusar pautas entre módulos
  - Futura migración a JSON/DB con cero impacto en las vistas
"""


# ─────────────────────────────────────────────────────────────────────────────
# PROTOCOLOS MINSAL (PREXOR, PLANESI, HIC, UV, CEAL-SM)
# ─────────────────────────────────────────────────────────────────────────────
PAUTAS_PROTOCOLOS = {
    "PREXOR (Ruido)": [
        "¿Existe creación de carpeta del protocolo de PREXOR en la faena?",
        "¿Se encuentra en la carpeta el material legal de protocolo a implementar?",
        "¿Cuenta con carta de encargado de protocolo y su respectivo curso de aprobación OAL?",
        "¿Empresa aplica Ficha Cualitativa de exposición a Ruido por ISP?",
        "¿Se encuentra dentro del programa de trabajo del CPHS actividades del protocolo?",
        "¿Existe sistema de gestión en la faena para la implementación del protocolo de PREXOR?",
        "¿Existe estudio previo de RUIDO ejecutada en la faena?",
        "¿Existe informe de identificación de peligro de exposición a RUIDO por parte del OAL?",
        "¿Se cumple con los plazos de las medidas establecidas en el informe técnico del OAL?",
        "¿Se realiza un mapeo de riesgos del agente propio con mediciones realizadas por el OAL?",
        "¿Se envía carta a trabajador para que asista a control de egreso en OAL?",
        "¿Existe programa de protección auditiva difundido al personal expuesto en base a IT del OAL?",
        "¿Se realizó la difusión del mapeo de riesgo del mandate al personal expuesto en terreno?",
        "¿Se verifica en terreno el uso adecuado y correcto de los EPP para ruido?",
        "¿Se mantiene registro de entrega y recambio de equipos de protección personal para ruido?",
        "¿Existe certificación de los EPP utilizados por el personal en terreno validados por el ISP?",
        "¿Existe programa de capacitación anual que incorpore temáticas para el agente ruido?"
    ],
    "PLANESI (Sílice)": [
        "¿Mantiene registro de entrega de material por OAL?",
        "¿Existe creación de carpeta del protocolo de Sílice en la faena?",
        "¿Se encuentra en la carpeta el material legal de protocolo a implementar?",
        "¿Cuenta con carta de encargado de protocolo y su respectivo curso de aprobación OAL?",
        "¿Cuenta con encuesta ISP PLANESI realizada por su OAL?",
        "¿Existe informe de identificación de peligro de exposición a sílice por parte del OAL?",
        "¿Se realiza Carta Gantt con fechas establecidas y responsables de implementación de medidas?",
        "¿Se encuentran dentro del programa de trabajo del CPHS actividades del protocolo?",
        "¿Se encuentra ejecutada al día la cualitativa de sílice del contrato?",
        "¿Se han ejecutado las medidas de control de las evaluaciones cuantitativas?",
        "¿Existe un sistema de gestión para la implementación del protocolo de Sílice en la faena?",
        "¿Realiza la difusión del SGSST-SÍLICE, a todos los responsables en su implementación?",
        "¿Existe coordinación para el inicio del programa de vigilancia?",
        "¿Existe concordancia entre informe genérico e INE?",
        "¿Existe programa por escrito de mantención de los equipos y limpieza de cabinas en la faena?",
        "¿Tiene establecida la prohibición de comer y fumar en el puesto de trabajo?",
        "¿Se realiza difusión al personal sobre el programa de protección respiratoria?",
        "¿Se envía carta a trabajador para que asista a control de egreso en OAL?"
    ],
    "HIC (Hipobaria)": [
        "¿Existe creación de carpeta de HIC?",
        "¿Tiene exposición?",
        "¿Se encuentra en la carpeta el material legal de HIC?",
        "¿Existe Cualitativa de HIC?",
        "¿Se mantiene al día la INE del personal expuestos ocupacionales HIC?",
        "¿Personal expuesto se encuentra en PVM?"
    ],
    "UV (Radiación Solar)": [
        "¿Existe creación de carpeta del protocolo de radiación UV en faena?",
        "¿Se encuentra en la carpeta el material legal de radiación UV?",
        "¿Cuenta con carta de encargado de protocolo y su respectivo curso de aprobación ACHS?",
        "¿Se cuenta con identificación (cualitativa riesgo exposición UV)?",
        "¿Se realiza difusión de la guía técnica de radiación UV de origen solar personal de la empresa?",
        "¿Se encuentra dentro del programa de trabajo del CPHS, actividades del protocolo?",
        "¿Existe listado de personal que trabaja con exposición a radiación UV al dia que contenga?",
        "¿Existe panel de radiación UV en la faena al día con el índice de radiación actual?",
        "¿Existe certificación de los EPP utilizados en faena validados por el ISP?",
        "¿Se calendariza y programan horarios de trabajo según riesgos de exposición a RUV?",
        "¿El filtro solar a utilizar en la faena es mayor o igual al factor 30 (bloqueador solar)?",
        "¿Existe lista de verificación y control de riesgo UV?"
    ],
    "CEAL-SM (Psicosocial)": [
        "¿Existe la carpeta del Protocolo Psicosocial?",
        "¿Se encuentra en la carpeta el material legal de Protocolo Psicosocial a implementar?",
        "¿Se encuentran dentro del programa de trabajo del CPHS actividades del protocolo?",
        "¿Existe difusión del Protocolo Psicosocial?",
        "¿Se conformó el comité de aplicación?",
        "¿Tiene acta de conformación del comité?",
        "¿Tiene la Carta Gantt de programación del proceso?",
        "¿Cuenta con Bitácora de reuniones y acuerdos del comité?",
        "¿Realizó difusión y sensibilización?",
        "¿Realizó aplicación de encuesta/cuestionario?",
        "¿Tiene registro de aplicación de la encuesta?",
        "¿Desarrolló el Análisis de resultados y Diseño de medidas?",
        "¿Los trabajadores expuestos se encuentran en Programa de Vigilancia de la Salud?",
        "¿Conformó el grupo de discusión?",
        "¿Cuenta con informe con medidas según resultado?",
        "¿Ejecutó las Medidas?",
        "¿Tiene un Plan de ejecución con responsable y fecha de cumplimiento por cada dimensión?",
        "¿Realiza Monitoreo y Verificación de las medidas?"
    ]
}

# ─────────────────────────────────────────────────────────────────────────────
# DS 44/2025 — Formulario Único de Fiscalización (FUF) SUSESO
# ─────────────────────────────────────────────────────────────────────────────
PAUTA_DS44 = [
    "AMBITO I: Gestión Preventiva (SGSST)",
    "¿Cuenta la entidad empleadora con una política de seguridad y salud en el trabajo escrita?",
    "¿La política de SST se encuentra difundida a todas las personas trabajadoras?",
    "¿Existe un diagnóstico de la situación de seguridad y salud en el trabajo de la entidad?",
    "¿El diagnóstico considera la identificación de deficiencias y oportunidades de mejora?",
    "¿Cuenta con una estructura organizacional para la gestión de la SST (responsables)?",
    "¿Existe un planificación anual de actividades preventivas basada en el diagnóstico?",
    "¿Se han asignado recursos (humanos, financieros, técnicos) para la gestión preventiva?",
    "¿Existen mecanismos de seguimiento y evaluación del cumplimiento de la planificación?",
    "¿Se realizan auditorías o revisiones periódicas del sistema de gestión?",
    "¿Se cuenta con un registro actualizado de la accidentabilidad y enfermedades profesionales?",
    "AMBITO II: Identificación de Peligros y Evaluación de Riesgos (MIPER)",
    "¿Cuenta la entidad con una Matriz de Identificación de Peligros (MIPER)?",
    "¿La MIPER abarca la totalidad de los procesos, tareas y puestos de trabajo?",
    "¿Se identifican peligros higiénicos (Ruido, Sílice, Ergonómicos, etc.) en la matriz?",
    "¿La evaluación de riesgos considera factores de riesgo psicosocial (CEAL-SM)?",
    "¿Se han evaluado los riesgos de violencia y acoso laboral (Ley Karin)?",
    "¿La MIPER incorpora la perspectiva de género en la evaluación de riesgos?",
    "¿Se han identificado y evaluado los riesgos asociados al teletrabajo (si aplica)?",
    "¿La matriz de riesgos se actualiza ante cambios en los procesos o accidentes graves?",
    "¿La MIPER está disponible en los lugares de trabajo para consulta?",
    "¿Se ha informado a los trabajadores sobre los resultados de la evaluación de riesgos?",
    "AMBITO III: Planificación y Programa de Trabajo Preventivo",
    "¿Existe un Programa de Trabajo Preventivo por centro de trabajo o faena?",
    "¿El programa incluye objetivos técnicos mensurables para el control de riesgos?",
    "¿Se definen responsables específicos para cada actividad del programa?",
    "¿El programa cuenta con plazos de ejecución definidos y verificables?",
    "¿Se incluyen actividades de inspección y observación de seguridad en el programa?",
    "¿Se contempla el mantenimiento preventivo de equipos e instalaciones?",
    "¿Existe registro del cumplimiento de las actividades programadas?",
    "¿Se difunden los resultados del cumplimiento del programa al CPHS/Delegado?",
    "AMBITO IV: Organización Preventiva (CPHS / Delegados)",
    "¿Se ha constituido el Comité Paritario de Higiene y Seguridad (si hay >25 trabajadores)?",
    "¿El CPHS cuenta con sus actas de constitución vigentes ante la Inspección del Trabajo?",
    "¿El Comité Paritario sesiona mensualmente de forma ordinaria?",
    "¿El CPHS cuenta con un programa de trabajo anual propio?",
    "¿El Comité Paritario participa en la investigación de accidentes del trabajo?",
    "¿Se ha designado un Delegado de SST si hay entre 10 y 25 trabajadores?",
    "¿El Delegado de Seguridad cumple con sus funciones de vigilancia y reporte?",
    "¿Existe el Reglamento Interno de Orden, Higiene y Seguridad (RIOHS) actualizado?",
    "¿Se ha entregado copia del RIOHS a todos los trabajadores (con registro)?",
    "¿El RIOHS incluye sanciones por incumplimiento de normas de seguridad?",
    "AMBITO V: Información y Capacitación",
    "¿Se garantiza la información oportuna (ex ODI) sobre riesgos a todo trabajador nuevo?",
    "¿Existen registros firmados de la información sobre riesgos entregada?",
    "¿Se informa sobre los métodos de trabajo correctos para cada actividad?",
    "¿Existe un programa de capacitación anual para todas las personas trabajadoras?",
    "¿La capacitación considera temas técnicos específicos según los riesgos del cargo?",
    "¿Se capacita a los integrantes del CPHS o al Delegado en sus funciones legales?",
    "¿Se cuenta con registros de asistencia y evaluación de las capacitaciones realizadas?",
    "¿La capacitación incorpora el enfoque de género y prevención de violencia?",
    "AMBITO VI: Medidas de Prevención y Protección",
    "¿Se privilegian las medidas de ingeniería (control en la fuente) sobre los EPP?",
    "¿Se cuenta con Procedimientos de Trabajo Seguro (PTS) para las tareas críticas?",
    "¿Los PTS están difundidos y disponibles para los trabajadores en terreno?",
    "¿Se entregan Elementos de Protección Personal (EPP) adecuados al riesgo evaluado?",
    "¿Existe registro de cargo y entrega de EPP para cada trabajador?",
    "¿Se realiza supervisión efectiva del uso correcto de los EPP en terreno?",
    "¿Se cuenta con servicios higiénicos (baños, duchas) según el DS 594?",
    "¿Existen comedores e instalaciones adecuadas para la alimentación del personal?",
    "AMBITO VII: Investigación de Accidentes y Emergencias",
    "¿Se investigan todos los accidentes del trabajo mediante el Método del Árbol de Causas?",
    "¿Se cuenta con informes de investigación de accidentes que identifiquen causas raíz?",
    "¿Se implementan medidas correctivas tras un accidente o incidente?",
    "¿Existe un Plan de Emergencia y Desastres actualizado y probado (simulacros)?",
    "¿Se cuenta con equipamiento para primera respuesta (extintores, botiquines)?",
    "¿Se realiza seguimiento a los programas de vigilancia médica de los trabajadores?"
]

# ─────────────────────────────────────────────────────────────────────────────
# CPHS — Nivel Inicial (DS 44 / SUSESO)
# ─────────────────────────────────────────────────────────────────────────────
PAUTA_CPHS_INICIAL = [
    "AMBITO 1: Proceso de Elección y Designación",
    "1.1.- ¿Se realizaron las elecciones de CPHS con votación presencial o electrónica, voto con 6 espacios en blanco, y se generó un acta de elección?",
    "1.2.- ¿Se ha levantado un acta de constitución del CPHS y registrada en el sitio web de la DT o SUSESO?",
    "1.3.- ¿La entidad empleadora designó a sus 6 representantes titulares y suplentes con criterios de equidad de género?",
    "1.4.- ¿Se demuestra que las empresas elegidas para constituir el CP de faena fueron las correctas según el D.S. 76?",
    "1.5.- ¿Los integrantes del CPHS no superan los 2 periodos consecutivos?",
    "AMBITO 2: Constitución",
    "2.1.- ¿Los representantes de las personas trabajadoras son mayores de 18 años, saben leer/escribir, tienen 1 año de antigüedad y curso OPR?",
    "2.2.- ¿Fueron constituidas las comisiones de trabajo (Inspecciones, Investigación de accidentes, Capacitación) y formalizadas en acta?",
    "AMBITO 3: Actas",
    "3.1.- ¿Se cuenta con las 3 últimas actas de reunión ordinarias para revisión de contenido?",
    "AMBITO 4: Programa de Trabajo",
    "4.1.- ¿El Programa de trabajo se confeccionó en base a la MIPER con fechas y responsables, y las actividades del último mes fueron ejecutadas?",
    "4.2.- ¿El % de cumplimiento del Programa de Trabajo se mide de forma acumulada y queda registrado en el acta?",
    "AMBITO 5: Capacitación y Difusión",
    "5.1.- ¿Todos los integrantes (titulares y suplentes) cuentan con el curso de orientación en prevención de riesgos (OPR)?",
    "5.2.- ¿Los integrantes titulares cuentan con el curso de Método de Investigación de accidentes Árbol de Causas?",
    "5.3.- ¿El CPHS ha capacitado a los trabajadores en riesgos críticos (MIPER) con una cobertura de al menos el 80%?",
    "5.4.- ¿La comisión de capacitación vinculó su programa con al menos 3 de las tareas de mayor riesgo de la empresa?",
    "5.5.- ¿Al menos un titular de cada lado cuenta con el curso de formación de integrantes de CPHS (20 hrs)?",
    "5.6.- ¿El acta de constitución y actas ordinarias fueron enviadas a la máxima autoridad del centro de trabajo?",
    "5.7.- ¿Se publican las actas, programa de trabajo y actividades a través de paneles, intranet u otros medios?",
    "5.8.- ¿El CPHS recibe formalmente el Programa de Trabajo en prevención de riesgos laborales de la entidad empleadora?",
    "AMBITO 6: Investigación de Accidentes",
    "6.1.- ¿El comité lleva un registro de accidentes, incidentes peligrosos y estadísticas de enfermedades profesionales?",
    "6.2.- En faenas sin Depto. Prevención, ¿se integra a la investigación un representante de la entidad empleadora y del accidentado?",
    "6.3.- ¿El CPHS investiga los accidentes bajo la metodología de Árbol de Causas (MAC)?",
    "6.4.- ¿Las medidas correctivas derivadas de investigaciones están siendo tratadas y cuentan con prioridad asignada?",
    "AMBITO 7: Inspecciones y Observaciones",
    "7.1.- ¿La comisión de inspecciones desarrolló un programa basado en la MIPER y casuística de los últimos 12 meses?",
    "7.2.- ¿Se han realizado las inspecciones de seguridad según el programa definido?",
    "7.3.- ¿Se han considerado y realizado inspecciones de seguridad a empresas contratistas?",
    "7.4.- ¿El CPHS ha verificado mediante observaciones el cumplimiento de los PTS para tareas críticas?",
    "7.5.- ¿Las medidas correctivas de condiciones inseguras se ordenan según su criticidad y prioridad?",
    "7.6.- ¿El programa de trabajo considera inspecciones de condiciones sanitarias básicas (D.S. 594)?",
    "AMBITO 8: Reglamento Interno",
    "8.1.- ¿El CPHS revisó el Reglamento Interno (RIOHS) y levantó observaciones sobre seguridad y salud?",
    "AMBITO 9: Fiscalización",
    "9.1.- ¿Se han registrado las fiscalizaciones (SEREMI, SUSESO, DT) en actas ordinarias y se realiza seguimiento a las medidas?"
]
