[server]
maxUploadSize = 25
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#0A58CA"
backgroundColor = "#F4F6F9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A192F"
font = "sans serif"

[browser]
gatherUsageStats = false
